apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  namespace: cloudlab
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'django'
        kubernetes_sd_configs:
        - role: endpoints
        relabel_configs:
        - source_labels: [__meta_kubernetes_namespace]
          action: keep
          regex: cloudlab
        - source_labels: [__meta_kubernetes_service_name]
          action: keep
          regex: django-service
